services:
  frontend:
    image: ghcr.io/abrahamkoloboe27/demo-cicd-atut-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - demo-cicd-atut-network
    volumes:
      - frontend:/usr/share/nginx/html
  backend:
    image: ghcr.io/abrahamkoloboe27/demo-cicd-atut-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - demo-cicd-atut-network
    volumes:
      - backend:/app

networks:
  demo-cicd-atut-network:
    driver: bridge

volumes:
  frontend:
  backend: