site_name: "Projet de Classification de Fruits"
site_url: "https://abrahamkoloboe27.github.io/Demo-CICD-With-Github-Actions-ATUT-SN"
site_description: "Documentation complète du projet, incluant Docker, Docker Compose, GitHub Actions, et CI/CD"
repo_name: abrahamkoloboe27/Demo-CICD-With-Github-Actions-ATUT-SN
repo_url: https://abrahamkoloboe27.github.io/Demo-CICD-With-Github-Actions-ATUT-SN

copyright: Copyright &copy; 2024 Abraham Koloboe

theme:
  name: readthedocs
  language: 'fr'

nav:
  - Accueil: index.md
  - Getting started:
      - Docker et Docker Compose: docker-et-docker-Compose.md
      - CI/CD: ci-cd.md
      - GitHub Actions: github-actions.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search